---
- name: Starting building splunk bots server
  hosts: bots
  become: true
  roles:
    - role: splunk-base
    - role: splunk-bots

  vars:
    - splunk_bots_version: botsv3
    #- splunk_botsv2_dataset: attack_only
    #- splunk_botsv1_dataset: attack_only