---
- name: Set facts for systemd servers
  set_fact:
    notify_task: "restart splunk systemd"
  when: ansible_service_mgr == "systemd"

- name: Set facts for non systemd servers
  set_fact:
    notify_task: "restart splunk service"
  when: ansible_service_mgr != "systemd"

- name: check content of splunk_bots_version
  fail:
    msg: splunk_bots_version has to be either botsv3 or botsv2
  when:
    - splunk_bots_version != "botsv2"
    - splunk_bots_version != "botsv3"

- name: check content of splunk_botsv2_dataset
  fail:
    msg: splunk_botsv2_dataset has to be either full or attack_only when botsv2 is used
  when:
    - splunk_bots_version == "botsv2"
    - splunk_botsv2_dataset != "full"
    - splunk_botsv2_dataset != "attack_only"

- import_tasks: install_apps.yml
- import_tasks: get_dataset.yml
- import_tasks: scoreboard.yml
- import_tasks: users.yml
- import_tasks: load_data.yml
