---
- name: Download Splunk install deb
  get_url:
    url: "{{ splunk_url_deb }}"
    dest: /tmp/splunk.deb

- name: Checking if Splunk is installed
  stat: "path={{ splunk_base }}/bin/splunk"
  register: splunk_path

- name: Splunk is installed
  debug: msg='splunk is installed at {{ splunk_base }}'
  when: splunk_path.stat.exists

- name: Get Splunk version
  shell: "echo $(cat {{ splunk_base }}/etc/splunk.version | grep VERSION | cut -d'=' -f2)"
  register: splunk_version_check
  changed_when: False
  check_mode: no
  when: splunk_path.stat.exists

- name: Install Splunk from .deb package
  apt: "deb=/tmp/splunk.deb"
  register: splunk_installed

- name: Sets default acl for splunk on /var/log
  shell: setfacl -Rm u:splunk:rX,d:u:splunk:rX /var/log

- name: Add sudoers config to allow service restarts as splunk user
  copy:
    content: |
      %splunk ALL = (root) NOPASSWD: /bin/systemctl start Splunkd.service
      %splunk ALL = (root) NOPASSWD: /bin/systemctl stop Splunkd.service
      %splunk ALL = (root) NOPASSWD: /bin/systemctl restart Splunkd.service
    dest: "/etc/sudoers.d/splunk"
    owner: root
    group: root
    mode: '0440'