---
# Configure Splunk Cluster nodes
- name: Include Secrets
  include_vars: "secrets.yml"

- name: Set facts for systemd servers
  set_fact:
    service_file: "/etc/systemd/system/multi-user.target.wants/splunkd.service"
    notify_task: "restart splunk systemd"
    tpl_src: "splunk.service.j2"
    tpl_dest: "/etc/systemd/system/multi-user.target.wants/splunkd.service"
  when: ansible_service_mgr == "systemd"

- name: Set facts for non systemd servers
  set_fact:
    service_file: "/etc/init.d/splunk"
    notify_task: "restart splunk service"
    tpl_src: "splunk.init.j2"
    tpl_dest: "/etc/init.d/splunk"
  when: ansible_service_mgr != "systemd"

- import_tasks: kernel.yml
- import_tasks: deploy.yml
- import_tasks: config.yml
- import_tasks: service.yml